In [113]:
import numpy as np
import sys

# Dasar

In [12]:
a = np.array([1, 2, 3], dtype='int32') #array 1 dimensi. Kita bisa menentukan tipe data dan ukuran yang akan
                                       #digunakan array dengan cara, menambah parameter dtype='ukuran&tipeData'
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]]) #array 2 dimensi
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## Mengecek Dimensi dari Array Numpy

In [6]:
#mengecek dimensi dari array numpy
print(a.ndim)
print(b.ndim)

1
2


## Mengecek Bentuk Array (berapa kali berapa)

In [7]:
#mengecek bentuk array (berapa kali berapa)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


## Mengecek Berapa Banyak Memory yang Digunakan Array Sekaligus Tipe Datanya (dalam bit)

In [13]:
#mengecek berapa banyak memory yang digunakan array sekaligus tipe datanya(dalam bit, dan 1 byte = 8 bit)
print(a.dtype) #outputnya int32 karena saat pembuatan array kita sudah menentukan tipe dan ukurannya
print(b.dtype)

int32
float64


## Mengecek Ukuran Memory yang Digunakan Array (dalam byte)

In [14]:
#mengecek ukuran memory yang digunakan array (dalam byte)
print(a.itemsize)
print(b.itemsize)

4
8


## Mengecek Berapa Banyak Elemen di Dalam Array

In [15]:
#mengecek berapa banyak elemen di dalam array
print(a.size)
print(b.size)

3
6


## Mengecek Ukuran Total Array

In [17]:
#mengecek ukuran total array
print(a.size * a.itemsize)
print(b.size * b.itemsize)

#cara lain (hasilnya sama)
print(a.nbytes)
print(b.nbytes)

12
48
12
48


# Mengakses/Merubah Elemen yang Spesifik, Baris, Kolom, Dll

In [18]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


## Mendapatkan Elemen Spesifik di Dalam Array [baris, kolom]

In [20]:
print(a[1, 5]) #mendapatkan elemen 13 pada baris dengan indeks 1 kolom dengan indeks 5
print(a[1, -2])

13
13


## Mendapatkan Baris Spesifik di Dalam Array

In [21]:
print(a[0,:]) #mendapatkan baris dengan indeks 0

[1 2 3 4 5 6 7]


## Mendapatkan Kolom Spesifik di Dalam Array

In [24]:
print(a[:,2]) #mendapatkan kolom dengan indeks 2

[ 3 10]


## [startIndex:endIndex:stepSize]

In [25]:
print(a[0, 1:-1:2]) #baris dengan indeks 0, dimulai dari indeks 1, berakhir pada indeks -1, lompat setiap 2 indeks

[2 4 6]


## Merubah Elemen di Dalam Array

In [26]:
a[1, 5] = 20 #elemen di dalam indeks baris 1 dan indeks kolom 5 dirubah nilainya menjadi 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [27]:
a[:,2] = 5 #semua elemen di kolom dengan indeks 2 dirubah nilainya menjadi 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [28]:
a[:,3] = [1,2] #elemen di kolom indeks 3 dirubah menjadi 1 dan 2
print(a)

[[ 1  2  5  1  5  6  7]
 [ 8  9  5  2 12 20 14]]


contoh lain dengan bentuk array 3 dimensi

In [30]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
#mendapatkan elemen spesifik
print(b[0,1,1])
print(b[:,1,:])
print(b[:,0,:])

4
[[3 4]
 [7 8]]
[[1 2]
 [5 6]]


In [33]:
#merubah elemen 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Menginisialisasi Berbagai Macam Jenis Array

## Menginisialisasi Array(Matriks) yang Isinya Semuanya 0

In [36]:
x = np.zeros(5) #matriks 0 satu dimensi
y = np.zeros((3,4)) #matriks 0 dua dimensi
z = np.zeros((2,3,3)) #matrik 0 tiga dimensi
#jika ingin membuat yang lebih dari 3 dimensi juga bisa

print(x)
print('----------')
print(y)
print('----------')
print(z)

[0. 0. 0. 0. 0.]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Menginisialisasi Array(Matriks) yang Isinya Semuanya 1

In [37]:
x = np.ones(5) #matriks 1 satu dimensi
y = np.ones((3,4)) #matriks 1 dua dimensi
z = np.ones((4,2,2)) #matrik 1 tiga dimensi
#jika ingin membuat yang lebih dari 3 dimensi juga bisa

print(x)
print('----------')
print(y)
print('----------')
print(z)

[1. 1. 1. 1. 1.]
----------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


## Menginisialisasi Array(Matriks) yang Isinya Sama Semua

In [38]:
arr = np.full((2,2), 99) #np.full((dimensi array), nilai yang ingin dimasukkan)
print(arr)

[[99 99]
 [99 99]]


In [40]:
#merubah array dibawah ini menjadi isinya sama semua (full_like)
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
fl = np.full_like(a, 5)
print(fl)

#selain full_like kita juga bisa menggunakan cara berikut untuk hasil yang sama
fl2 = np.full(a.shape, 4)
print(fl2)

[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


## Menginisialisasi Array(Matriks) yang Isinya Random Decimal Number

In [41]:
rdc = np.random.rand(4,2) #4 dan 2 adalah dimensi atau shapenya
print(rdc)

[[0.76970954 0.00481765]
 [0.41408273 0.34219942]
 [0.76345088 0.07124326]
 [0.52869846 0.57795063]]


## Menginisialisasi Array(Matriks) yang Isinya Random Integer Number

In [43]:
rin = np.random.randint(7, size = (3,3)) #7 adalah nilai maksimal yang akan dirandom. dan size adalah dimensinya
print(rin)

[[1 0 4]
 [5 5 1]
 [4 2 0]]


In [44]:
rin = np.random.randint(4,7, size = (3,3)) #isi randoman hanya boleh dalam range 4-7 dan size adalah dimensinya
print(rin)

[[6 6 4]
 [4 4 5]
 [5 5 4]]


## Menginisialisasi Array(Matriks) yang Isinya Random Float Number

In [127]:
np.random.random((2,2))

array([[0.21226194, 0.78853055],
       [0.18260382, 0.28270181]])

## Membuat Array yang Isinya Urut dari 0 sampai Batas yang Ditentukan

In [110]:
u = np.arange(5) #membuat array yang isinya 0 sampai 4
u

array([0, 1, 2, 3, 4])

## Menginisialisasi Matriks Identitas

In [45]:
np.identity(5) #shapenya 5 x 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Repeat an Array

In [46]:
arr = np.array([9,8,7])
r1 = np.repeat(arr,3) #akan diulang 3 kali
print(r1)

[9 9 9 8 8 8 7 7 7]


In [47]:
arr = np.array([[1,2,3]]) # 2 dimensi
r1 = np.repeat(arr,3, axis=0) #bila axis = 0 maka bentuk arraynya akan ditata secara vertikal  
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
arr = np.array([[1,2,3]]) # 2 dimensi
r1 = np.repeat(arr,3, axis=1) #bila axis = 1 maka bentuk arraynya akan ditata secara horizontal 
print(r1)

[[1 1 1 2 2 2 3 3 3]]


# Membuat Pola dengan Array

In [50]:
output = np.ones((5,5))
print(output)
print('----------')

z = np.zeros((3,3))
z[1,1] = 9
print(z)
print('----------')

output[1:4,1:4] = z #output[1:-1,1:-1] seperti ini hasilnya juga akan sama
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----------
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
----------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Hati-Hati Saat Mengcopy Array!!!!!

In [51]:
a = np.array([1,2,3])
b = a
b[0] = 100 #merubah elemen pertama pada array b
print(b)
print(a) #saat kita memprint a, seharusnya hasilnya berbeda dengan b, karena elemen pertama pada b sudah diganti

[100   2   3]
[100   2   3]


In [52]:
#untuk mencegah hal di atas, berikut adalah solusinya
a = np.array([1,2,3])
b = a.copy()
b[0] = 100 
print(b)
print(a) 

[100   2   3]
[1 2 3]


# Operasi Matematika pada Array

In [53]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [54]:
a + 2 #setiap elemen di dalam array ditambah 2

array([3, 4, 5, 6, 7])

In [55]:
a - 2 #setiap elemen di dalam array dikurang 2

array([-1,  0,  1,  2,  3])

In [56]:
a * 2 #setiap elemen di dalam array dikali 2

array([ 2,  4,  6,  8, 10])

In [57]:
a / 2 #setiap elemen di dalam array dibagi 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [58]:
b = np.array([1,0,1,0,1])
a + b

array([2, 2, 4, 4, 6])

In [59]:
a ** 2 #setiap elemen di dalam array dipangkat 2

array([ 1,  4,  9, 16, 25])

In [60]:
np.sin(a) #mencari nilai sin dari setiap elemen di dalam array

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [61]:
np.cos(a) #mencari nilai cos dari setiap elemen di dalam array

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

# Aljabar Linear 

In [119]:
A = np.array([[1,2,3],[4,5,6]])
B = np.full((2,3),5)
v = np.array([7,8,9])
print(A)
print('----------')
print(B)
print('----------')
print(v)

[[1 2 3]
 [4 5 6]]
----------
[[5 5 5]
 [5 5 5]]
----------
[7 8 9]


In [115]:
#Penjumlahan matriks A + B
A + B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [116]:
#Pengurangan matriks A - B
A - B

array([[-4, -3, -2],
       [-1,  0,  1]])

In [117]:
#Perkalian matriks A * B (Perkaliannya per elemen, karena sebenarnya  A & B tidak memenuhi syarat perkalian matriks)
A * B

array([[ 5, 10, 15],
       [20, 25, 30]])

In [118]:
#Pembagian matriks A / B
A / B

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [120]:
#Perkalian matriks (yang memenuhi syarat)
print(np.dot(A, v))
print(A @ v) #cara lain perkalian matriks yang memenuhi syarat

[ 50 122]
[ 50 122]


In [122]:
#Mencari Transpose (baris menjadi kolom, dan kolom menjadi baris) Matriks
print(A.T)
print('----------')
print(B.T)

[[1 4]
 [2 5]
 [3 6]]
----------
[[5 5]
 [5 5]
 [5 5]]


In [62]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

#karena 2 matriks di atas tidak memenuhi syarat agar bisa dikali maka tidak bisa dikali. tapi perkalian tetap bisa
#dilakukan menggunakan fungsi matmul() matrix multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [123]:
#Mencari Determinan Matriks
c = np.identity(3) #membuat matriks identitas
print(np.linalg.det(c)) #mencari determinan dari suatu matriks

d = np.array([[3,2],[4,1]])
print(np.linalg.det(d))

e =np.array([[4,1,0],[1,3,2],[0,2,5]])
print(np.linalg.det(e))

1.0
-4.999999999999999
38.99999999999999


In [126]:
#Mencari Invers Matriks (misalnya matriks A, maka inversnya A pangkat -1, atau 1 per determinan A)
D = np.array([[1,2],[3,4]])
print(np.linalg.det(D)) #melihat determinan 
print(np.linalg.inv(D)) #mencari invers matriks D
print('----------')

print(D @ np.linalg.inv(D)) #Mencari D x D pangkat -1 = I
print('----------')
print(np.round(D @ np.linalg.inv(D))) #membulatkan perhitungan di atas

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
----------
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
----------
[[1. 0.]
 [0. 1.]]


# Statistik dengan Numpy

In [67]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
#mencari nilai minimum pada array
print(np.min(stats))
print(np.min(stats, axis=1)) #kolom yang nilainya paling kecil
print(np.min(stats, axis=0)) #baris yang nilainya paling kecil

1
[1 4]
[1 2 3]


In [72]:
#mencari nilai maksimum pada array
print(np.max(stats))
print(np.max(stats, axis=1)) #kolom yang nilainya paling besar
print(np.max(stats, axis=0)) #baris yang nilainya paling besar

6
[3 6]
[4 5 6]


In [104]:
#menjumlahkan setiap elemen di dalam array
print(np.sum(stats))
print(stats.sum()) #hasilnya sama dengan di atas
print(np.sum(stats, axis=1))
print(stats.sum(axis=1))
print(np.sum(stats, axis=0))
print(stats.sum(axis=0))

21
21
[ 6 15]
[ 6 15]
[5 7 9]
[5 7 9]


In [106]:
#mencari rata rata
print(stats.mean())
print(stats.mean(axis=1))
print(stats.mean(axis=0))

3.5
[2. 5.]
[2.5 3.5 4.5]


In [107]:
#mencari standar deviasi
print(stats.std())
print(stats.std(axis=1))
print(stats.std(axis=0))

1.707825127659933
[0.81649658 0.81649658]
[1.5 1.5 1.5]


# Reorganisasi Array

In [76]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)
print('----------')

after = before.reshape((8,1))
after2 = before.reshape((4,2))
after3 = before.reshape((2,2,2))
print(after)
print('----------')
print(after2)
print('----------')
print(after3)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Menumpuk Vektor secara Vertikal

In [78]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

## Menumpuk Vektor secara Horizontal

In [79]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print('----------')
print(h2)
print('----------')

print(np.hstack((h1,h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------
[[0. 0.]
 [0. 0.]]
----------
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


# Lain Lain

## Memuat Data dari File

In [85]:
filedata = np.genfromtxt('numpydata.txt', delimiter=',') #delimiter adalah pemisah
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [84]:
filedata = np.genfromtxt('numpydata.txt', delimiter=',') #delimiter adalah pemisah
print(filedata)
print('-----------')
filedata.astype('int32') #merubah tipe data dari array ke tipe int
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
-----------
[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [88]:
filedata = np.genfromtxt('numpydata.txt', delimiter=',') #delimiter adalah pemisah
filedata.astype('int32') 
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

## Boolean Masking 

In [89]:
#Boolean Masking
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [93]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [94]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [90]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [92]:
#Mengindeks dengan menggunakan list
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [95]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [98]:
(~((filedata > 50) & (filedata < 100))) #bentuk not dari array diatas

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [112]:
#memilih elemen di dalam array menggunakan boolean
ar = np.array([1,2,3,4])
print(ar)
print(a[[True,False,False,True]])

[1 2 3 4]
[0 3]


## Advanced Indexing

In [101]:
mt = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30]])

#mengambil mengakses matriks [11,12]
#                            [13,14]
mt[2:4 , 0:2]

array([[11, 12],
       [16, 17]])

In [102]:
#mengambil diagonal miring kanan 2,8,14,20
mt[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [103]:
#mengambil 4,5 24,25 29,30
mt[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])